services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"

  payment-authorise-sqldata:
    image: "postgres"
    ports: 
      - "5432:5432"
    env_file:
      - Payment.Authorise/sqldata.env
    volumes:
      - ./authorise_schema.sql:/docker-entrypoint-initdb.d/authorise_schema.sql

  event-store-sqldata:
    image: "postgres"
    ports:
      - "5433:5433"
    env_file:
      - ./event_store_sqldata.env
    command: -p 5433
    volumes:
      - ./event_store_schema.sql:/docker-entrypoint-initdb.d/event_store_schema.sql

  payment-authorise:
    image: ${DOCKER_REGISTRY-}payment-authorise
    build:
      context: .
      dockerfile: Payment.Authorise/Dockerfile
    depends_on:
      - rabbitmq
      - event-store-sqldata
      - payment-authorise-sqldata

  payment-capture:
    image: ${DOCKER_REGISTRY-}payment-capture
    build:
      context: .
      dockerfile: Payment.Capture/Dockerfile
    depends_on:
      - rabbitmq
      - event-store-sqldata

  payment-gateway:
    image: ${DOCKER_REGISTRY-}payment-gateway
    ports:
      - "8080:80"
      - "443:443"
    build:
      context: .
      dockerfile: Payment.Gateway/Dockerfile
    depends_on:
      - rabbitmq
      - event-store-sqldata

  payment-refund:
    image: ${DOCKER_REGISTRY-}payment-refund
    build:
      context: .
      dockerfile: Payment.Refund/Dockerfile
    depends_on:
      - rabbitmq
      - event-store-sqldata

  payment-void:
    image: ${DOCKER_REGISTRY-}payment-void
    build:
      context: .
      dockerfile: Payment.Void/Dockerfile
    depends_on:
      - rabbitmq
      - event-store-sqldata